### ISSUE TITLE
Trouble working with jQuery 3.1.0?

### ISSUE THREAD

**Issue by ThePixelPixie** [vukhanhtruong/jquery-elastic-grid#8]
Not sure if there's a conflict with this newer version of jQuery, but I'm having difficulty getting this to work at all.  In my console I get the following errors:

"Uncaught SyntaxError: Unexpected token < elastic_grid.min.js:5"

"jQuery.Deferred exception: $(...).elastic_grid is not a function TypeError: $(...).elastic_grid is not a function
    at HTMLDocument.<anonymous> (http://path/index2.html?chapter=2:318:33)
    at j (http://path/js/jquery-3.1.0.min.js:2:29568)
    at k (http:/path/js/jquery-3.1.0.min.js:2:29882) undefined

jquery-3.1.0.min.js:2"

and 

"jquery-3.1.0.min.js:2 Uncaught TypeError: $(...).elastic_grid is not a function(anonymous function) @ index2.html?chapter=2:318j @ jquery-3.1.0.min.js:2k @ jquery-3.1.0.min.js:2

Any assistance you can provide would be greatly appreciated.

~Laura

**Comment by memmaina** [comment]
same here

**Comment by choubeyaakash77** [comment]
I'm using Jquery 3.3.1 and its working for me.
Try to enclose your initialization under `$` or `$(document).ready()`
